version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8123"  # Map directly to port 80 if needed
    environment:
      - ENVIRONMENT=production
      - WORKERS=4
      - HOST=0.0.0.0
      - PORT=8123
      - RELOAD=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/health"]
      interval: 30s
      timeout: 10s
      retries: 3