model:
  name: "all-MiniLM-L6-v2"
  cache_ttl: 86400
  batch_size: 32

redis:
  host: "localhost"
  port: 6379
  db: 0

server:
  host: "0.0.0.0"
  port: 8000

metrics:
  history_size: 100
  max_text_preview: 50

constants:
  DEFAULT_MODEL: "all-MiniLM-L6-v2"
  DEFAULT_CACHE_TTL: 86400
  MAX_TEXT_LENGTH: 10000
  METRICS_HISTORY_SIZE: 100
  QUEUE_TIMEOUT: 300
  MAX_RETRY_ATTEMPTS: 3