cache:
  max_size: 10000
  ttl: 3600  # 1 hour in seconds

worker:
  batch_size: 10
  max_queue_size: 1000
  processing_timeout: 30  # seconds

api:
  max_text_length: 10000
  rate_limit: 100  # requests per minute

logging:
  level: INFO
  file: embedding_service.log

metrics:
  enabled: true
  collection_interval: 60  # seconds